# Generated by Django 6.0.3 on 2026-04-05 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('deaf_family', 'Oilamda eshitish qobiliyati cheklangan shaxs bor'), ('professional', "Kasbiy maqsadda (tarjimon, o'qituvchi va h.k.)"), ('curiosity', 'Qiziqish va shaxsiy rivojlanish uchun'), ('student', "O'quv jarayonida talab qilinadi"), ('community', 'Jamiyatda yordam berish uchun')], default='', max_length=30)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Hech narsa bilmayman — noldan boshlayman'), ('basic', "Bir nechta so'z va harflarni bilaman"), ('intermediate', 'Oddiy gaplarni tushunaman va ishlataman')], default='', max_length=20)),
                ('daily_goal', models.CharField(blank=True, choices=[('casual', "Kuniga 5 daqiqa — bo'sh vaqtimda"), ('regular', 'Kuniga 15 daqiqa — muntazam'), ('serious', "Kuniga 30+ daqiqa — jiddiy o'rganaman")], default='', max_length=20)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
